export const FETCH_ROUTES = "FETCH_ROUTES";
export const FETCH_ROUTES_SUCCESS = "FETCH_ROuTES_SUCCESS";
export const FETCH_ROUTES_FAILED = "FETCH_ROUTES_FAILED"; 

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";

export const POST_DATA = "POST_DATA";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAILED = "POST_DATA_FAILED";

export const GET_DATA = "GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILED = "GET_DATA_FAILED";

export const UPDATE_DATA = "UPDATE_DATA";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS"; 
export const UPDATE_DATA_FAILED = "UPDATE_DATA_FAILED"; 

export const DELETE_DATA = "DELETE_DATA";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_FAILED = "DELETE_DATA_FAILED";

export const UPLOAD_DATA =  "UPLOAD_DATA";
export const UPLOAD_DATA_SUCCESS =  "UPLOAD_DATA_SUCCESS";
export const UPLOAD_DATA_FAILED = "UPLOAD_DATA_FAILED";

export const ROUTE_DATA = "ROUTE_DATA";
export const ROUTE_DATA_SUCCESS = "ROUTE_DATA_SUCCESS";
export const ROUTE_DATA_FAILED = "ROUTE_DATA_FAILED";


export const SET_COMMON_DROPDOWN = "SET_COMMON_DROPDOWN";

