// Auto-generated by hcms-generator — edit as needed
// Generated: 2026-05-03T08:59:06.342Z
import React, { useEffect, useRef, useState } from "react";
import Popup from '../../components/Popup';
import { API } from './_Service';
import {
    builderFieldsAction, useEntityAction,
    useEntitiesQuery, showDropDownFilterAction
} from '../../store/actions/httpactions';
import { PeopleOutline } from "../../deps/ui/icons";
import DataGrid, { getActions, GridToolbar, useGridApi } from '../../components/useDataGrid';
import { useSocketIo } from '../../components/useSocketio';
import ConfirmDialog from '../../components/ConfirmDialog';
import { AutoForm } from '../../components/useForm';
import PageHeader from '../../components/PageHeader';
import { formateISODateTime } from "../../services/dateTimeService";
import Loader from '../../components/Circularloading';
import { useDropDown } from "../../components/useDropDown";
import { useAppDispatch, useAppSelector } from "../../store/storehook";
import { useExcelReader } from "../../hooks/useExcelReader";

const DEFAULT_API = API.Candidate;  // ← _Service.ts mein add karo
const breakpoints = { size: { md: 3, sm: 6, xs: 12 } };

// ─── Mapper ───────────────────────────────────────────────────────────────────
const mapCandidate = (values) => {
    const map = { ...values };
    return {
        firstName: map.firstName,
        lastName: map.lastName,
        email: map.email,
        fkJobPostId: map.fkJobPostId?._id,
        resumeText: map.resumeText,
        skills: map.skills ?? [],
        experience: map.experience ?? [],
        totalExp: map.totalExp,
        similarityScore: map.similarityScore,
    };
};

// ─── Columns ──────────────────────────────────────────────────────────────────
const getColumns = () => [
    { field: '_id', headerName: 'Id', hide: true },
    { field: 'firstName', headerName: 'First Name', flex: 1 },
    { field: 'lastName', headerName: 'Last Name', flex: 1 },
    { field: 'email', headerName: 'Email', flex: 1 },
    { field: 'resumeText', headerName: 'Resume Text', flex: 1 },
    { field: 'skills', headerName: 'Skills', flex: 1 },
    { field: 'createdOn', headerName: 'Created On', flex: 1, valueGetter: ({ row }) => formateISODateTime(row.createdOn) },
    getActions(null)
];

// ─── Add Form ─────────────────────────────────────────────────────────────────
const AddCandidate = ({ openPopup, setOpenPopup, colData }) => {
    const formApi = useRef(null);
    const [loader, setLoader] = useState(false);
    const { jobposts } = useDropDown();
    const { addEntity } = useEntityAction();

    useEffect(() => {
        if (formApi.current && openPopup) formApi.current.resetForm();
    }, [openPopup]);

    const formData = [
        {
            elementType: inputfield,
            name: "firstName",
            label: "First Name",
            
           required:true,       
 validate: { errorMessage: "First Name is required" },
            defaultValue: "",
        },
        {
            elementType: inputfield,
            name: "lastName",
            label: "Last Name",
            
           required:true,       
 validate: { errorMessage: "Last Name is required" },
            defaultValue: "",
        },
        {
            elementType: inputfield,
            name: "email",
            label: "Email",
            
           required:true,       
 validate: { errorMessage: "Email is required" },
            defaultValue: "",
        },
        {
            elementType: "ad_dropdown",
            name: "fkJobPostId",
            label: "Job Post",
           required:true,       
 validate: { errorMessage: "Job Post is required" },
            dataName: "name",
            dataId: '_id',
            options: jobposts,
            defaultValue: null,
        },
        {
            elementType: inputfield,
            name: "resumeText",
            label: "Resume Text",
            
            defaultValue: "",
        },
        {
            elementType: "taginput",
            name: "skills",
            label: "Skills",
            defaultValue: []
        },
        {
            elementType: "taginput",
            name: "experience",
            label: "Experience",
            defaultValue: []
        },
        {
            elementType: "inputfield",
            name: "totalExp",
            type: "number",
            label: "Total Exp",
            defaultValue: 0,
        },
        {
            elementType: "inputfield",
            name: "similarityScore",
            type: "number",
            label: "Similarity Score",
            defaultValue: 0,
        },
        { elementType: "clearfix" }
    ];
    colData.current = formData;

    const handleSubmit = () => {
        const { getValue, validateFields } = formApi.current;
        if (validateFields()) {
            addEntity({ url: DEFAULT_API, data: [mapCandidate(getValue())] });
        }
    };

    return (
        <>
            <Loader open={loader} />
            <Popup
                title="Add Candidate"
                openPopup={openPopup}
                fullScreen={true}
                isEdit={false}
                keepMounted={true}
                addOrEditFunc={handleSubmit}
                setOpenPopup={setOpenPopup}
            >
                <AutoForm formData={formData} ref={formApi} isValidate={true} />
            </Popup>
        </>
    );
};

// ─── Main Page ────────────────────────────────────────────────────────────────
const Candidate = () => {
    const dispatch = useAppDispatch();
    const [openPopup, setOpenPopup]       = useState(false);
    const [selectionModel, setSelectionModel] = useState([]);
    const [sort, setSort]                 = useState({ sort: { createdAt: -1 } });
    const [gridFilter, setGridFilter]     = useState({ lastKey: null, limit: 10, page: 0, totalRecord: 0 });
    const [confirmDialog, setConfirmDialog] = useState({ isOpen: false, title: "", subTitle: "" });

    const excelColData = useRef([]);
    const gridApiRef   = useGridApi();
    const query        = useAppSelector(e => e.appdata.query.builder);

    const { setFile, excelData, getTemplate } = useExcelReader({
        formTemplate: excelColData.current,
        transform: mapCandidate,
        fileName: "Candidate.xlsx"
    });

    const { data, isLoading, refetch, totalRecord } = useEntitiesQuery({
        url: `${DEFAULT_API}/get`,
        data: {
            limit: gridFilter.limit,
            page: gridFilter.page + 1,
            lastKeyId: gridFilter.lastKey,
            ...sort,
            searchParams: { ...query }
        }
    }, {
        selectFromResult: ({ data, isLoading }) => ({
            data: data?.entityData,
            totalRecord: data?.totalRecord,
            isLoading
        })
    });

    const { removeEntity, addEntity } = useEntityAction();

    useEffect(() => {
        if (excelData) addEntity({ url: DEFAULT_API, data: excelData });
    }, [excelData]);

    useSocketIo("changeInCandidate", refetch);

    const handelDeleteItems = (ids) => {
        const idTobeDelete = Array.isArray(ids) ? ids.join(',') : ids;
        setConfirmDialog({
            isOpen: true,
            title: "Are you sure to delete this record?",
            subTitle: "You can't undo this operation",
            onConfirm: () => {
                removeEntity({ url: DEFAULT_API, params: idTobeDelete })
                    .then(() => setSelectionModel([]));
            },
        });
    };

    useEffect(() => {
        dispatch(showDropDownFilterAction({ employee: true }));
    }, [dispatch]);

    return (
        <>
            <PageHeader
                title="Candidate"
                enableFilter={true}
                handleUpload={(e) => setFile(e.target.files[0])}
                handleTemplate={getTemplate}
                subTitle="Manage Candidate"
                icon={<PeopleOutline fontSize="large" />}
            />
            <AddCandidate colData={excelColData} openPopup={openPopup} setOpenPopup={setOpenPopup} />
            <DataGrid
                apiRef={gridApiRef}
                columns={getColumns()}
                rows={data}
                page={gridFilter.page}
                checkboxSelection={false}
                disableSelectionOnClick={true}
                getRowHeight={() => 40}
                loading={isLoading}
                pageSize={gridFilter.limit}
                setFilter={setGridFilter}
                onSortModelChange={(s) =>
                    setSort({ sort: s.reduce((a, v) => ({ ...a, [v.field]: v.sort === 'asc' ? 1 : -1 }), {}) })
                }
                totalCount={totalRecord}
                toolbarProps={{ apiRef: gridApiRef, onAdd: () => setOpenPopup(true), selectionModel }}
                gridToolBar={GridToolbar}
                selectionModel={selectionModel}
                setSelectionModel={setSelectionModel}
            />
            <ConfirmDialog confirmDialog={confirmDialog} setConfirmDialog={setConfirmDialog} />
        </>
    );
};

export default Candidate;
