export const API = {
    Attendance: "attendance/amend",
    AttendanceInsert: "attendance/amend/insert",
    AttendanceRequest: "attendance/request",
    GetAttendanceDetail: "attendance/request/detail",
    ExemptionRequest: "attendance/exemption",
    GetExemptionDetail: "attendance/exemption/detail",
    Shift: "attendance/shift",
    ScheduleDetail: "attendance/schedule/scheduledetail",
    Schedule: "attendance/schedule",
    UpdateSchedule: "attendance/schedule/updateSchedule",
    Approval: "attendance/approval",
    ApprovalAction: "attendance/approval/action",
    // Designation: "employee/designation",
}